### ISSUE TITLE
Golden Carrot error.

### ISSUE THREAD

**Issue by MariusMRN** [BlockHorizons/BlockSniper#101] opened 2018-09-07 19:24 UTC
#### Description
I can open the menu, but another player can't. He's OP and he also using the gold carrot.

#### Versions
* PocketMine version: PocketMine-MP 3.2.2
* BlockSniper version: 7 september update.
* Game version: W10

#### Crashdump and/or console errors

http://prntscr.com/kru9cv

**Comment by Sandertv** [comment] 2018-09-07 20:28
Aware of it, I'm pushing a commit soon. This happens when an invalid block is provided. After it, the brush refuses to open. I have it fixed locally, I'll push and release a new version soon.

**Comment by Sandertv** [comment] 2018-09-07 20:32
The issue is fixed in BlockSniper 3.0.4. Thanks for your issue report!

**Closed by Sandertv** 2018-09-07 20:32 UTC
Labels: CATEGORY: Bug, STATUS: Fixed
