### ISSUE TITLE
Tree is invalid type

### ISSUE THREAD

**Issue by DerddyDert** [BlockHorizons/BlockSniper#49] opened 2017-04-10 05:21 UTC
#### Description
When I attempt 
/b type Tree
It says warning Shape or type not found.

#### Versions
* PocketMine version:
* BlockSniper version:
* Game version: PE/W10

#### Crashdump and/or console errors

```
```

**Comment by Sandertv** [comment] 2017-04-10 05:30
Could you try typing it lowercase?

**Comment by Sandertv** [comment] 2017-04-10 06:09
Also, because you didn't fill in the fields of the template, I can't resolve this issue. I need to know which version of BlockSniper you are using. Please do /bs ingame and tell me the version number.

**Comment by DerddyDert** [comment] 2017-04-10 12:59
Bs ver 1.3.1
Server ver Tesseract-1.2.0
Php 7.0.3
API 3.0.1
Game is PE
I did it in lower case. Can't seem to get tree to work. Everything else works great and is amazing. Now I only use mcedit to import schematics.

**Comment by Sandertv** [comment] 2017-04-10 13:05
That version might not feature the Tree type. Try grabbing the latest version from the Poggit CI or compile the zip yourself with Dev tools. It should be version 1.3.3.

**Comment by Sandertv** [comment] 2017-04-12 21:43
I'm closing this because I'm quite confident the Tree type just isn't implemented in your version yet. If you manage to reproduce this issue in the latest version, please re-open the issue.

**Closed by Sandertv** 2017-04-12 21:43 UTC
Labels: CATEGORY: Bug, STATUS: Unconfirmed

**Comment by derddy** [comment] 2017-04-13 07:05
I downloaded the latest version and was able to set the type as tree.
When using it it threw the following in console:
[Tesseract] [07:03:14] CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'BlockSniper v1.3.4': Class pocketmine\level\generator\object\Tree not found on BlockHorizons\BlockSniper\listeners\BrushListener
[Tesseract] [07:03:14] CRITICAL> ClassNotFoundException: "Class pocketmine\level\generator\object\Tree not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Sandertv** [comment] 2017-04-13 12:29
This is sadly an issue with Tesseract, which I can not resolve. Sorry.
